main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import (
    add_item_view,
    all_products_view,
    product_detail_view,
    select_category_to_add_product_view,
    edit_sizes_view,
    product_delete_view,
    product_edit_view,
    all_hats_view,
    all_outwear_view,
    all_pants_view,
    all_shoes_view,
    seller_products_on_sale_view,
    seller_shoes_on_sale_view,
    seller_pants_on_sale_view,
    seller_outwear_on_sale_view,
    seller_hats_on_sale_view,
    seller_withdrawn_from_sale_view,
    remove_product_from_sale,
    return_on_sale,
    add_to_shopping_cart,
    remove_from_shopping_cart,
    shopping_cart_view,
    buyer_favourites_view,
    add_to_favourites,
    remove_from_favourites,
)

urlpatterns = [
    # product CRUD
    path('select_category', select_category_to_add_product_view, name='select_category'),
    path('add_product/<slug:product_model_slug>', add_item_view, name='add_item'),
    path('catalogs/<slug:product_model_slug>/<slug:product_slug>', product_detail_view, name='item_detail'),
    path('edit_sizes/<slug:product_slug>', edit_sizes_view, name='edit_sizes'),
    path('delete_product/<slug:product_slug>', product_delete_view, name='product_delete'),
    path('edit_product/<slug:product_slug>', product_edit_view, name='product_edit'),
    # all products
    path('catalog/all_items', all_products_view, name='all_items'),
    path('catalog/hats', all_hats_view, name='all_hats'),
    path('catalog/outwear', all_outwear_view, name='all_outwear'),
    path('catalog/shoes', all_shoes_view, name='all_shoes'),
    path('catalog/pants', all_pants_view, name='all_pants'),
    # seller_profile
    path('users/seller_profile/products_on_sale', seller_products_on_sale_view, name='seller_products_on_sale'),
    path('users/seller_profile/shoes_on_sale', seller_shoes_on_sale_view, name='seller_shoes_on_sale'),
    path('users/seller_profile/pants_on_sale', seller_pants_on_sale_view, name='seller_pants_on_sale'),
    path('users/seller_profile/outwear_on_sale', seller_outwear_on_sale_view, name='seller_outwear_on_sale'),
    path('users/seller_profile/hats_on_sale', seller_hats_on_sale_view, name='seller_hats_on_sale'),
    path('users/seller_profile/withdrawn_from_sale', seller_withdrawn_from_sale_view, name='seller_withdrawn_from_sale'),
    # buyer_profile
    path('users/buyer_profile/shopping_cart', shopping_cart_view, name='shopping_cart'),
    path('users/buyer_profile/favourites', buyer_favourites_view, name='buyer_favourites'),
    # logic
    path('remove_from_on_sale/<slug:product_slug>', remove_product_from_sale, name='remove_product_from_sale'),
    path('return_on_sale/<slug:product_slug>', return_on_sale, name='return_on_sale'),
    path('add_to_shopping_cart/<slug:product_slug>', add_to_shopping_cart, name='add_to_shopping_cart'),
    path('remove_from_shopping_cart/<slug:product_slug>', remove_from_shopping_cart, name='remove_from_shopping_cart'),
    path('add_to_favourites/<slug:product_slug>', add_to_favourites, name='add_to_favourites'),
    path('remove_from_favourites/<slug:product_slug>', remove_from_favourites, name='remove_from_favourites')
]

users/urls.py
from django.urls import path
from .views import (
    StoreUserLogoutView,
    user_registration_view,
    buyer_profile_view,
    StoreUserLoginView,
    seller_profile_view,
)
app_name = 'user'
urlpatterns = [
    path('login/', StoreUserLoginView.as_view(), name='login'),
    path('signup/', user_registration_view, name='signup'),
    path('logout/', StoreUserLogoutView.as_view(), name='logout'),
    path('buyer_profile/', buyer_profile_view, name='buyer_profile'),
    path('seller_profile/', seller_profile_view, name='seller_profile')
]

store/views.py
from django.views.generic import (
    TemplateView,
)

from .forms import (
    SelectCategoryForm,
)

from django.shortcuts import (
    render,
)

from django.http import (
    HttpResponseRedirect,
    HttpResponseNotFound,
)
from django.contrib.auth.decorators import permission_required

from django.urls import reverse

from .models import (
    Hat,
    OutWear,
    Pants,
    Shoes,
)
from .shortcuts import (
    get_all_products,
    get_product_by_slugs,
    get_product_sizes_manager,
    is_seller_owner,
    get_product_model_by_model_slug,
    get_product_creation_form,
    get_product_by_slug,
    is_product_has_sizes,
    get_product_sizes_inlineformset,
    get_sizes_creation_formset,
    get_sizes_creation_formset_default_initial,
    get_product_edit_form,
    add_to_on_sale,
    get_seller_products_on_sale,
    pop_from_on_sale,
    get_seller_shoes_on_sale,
    get_seller_pants_on_sale,
    get_seller_outwear_on_sale,
    get_seller_hats_on_sale,
    get_seller_withdrawn_from_sale,
    is_seller_owner_of_product,
    add_product_code_to_buyer_shopping_cart,
    is_product_in_shopping_cart,
    remove_product_code_from_buyer_shopping_cart,
    get_buyer_shopping_cart_products,
    add_product_to_buyer_favourites,
    pop_product_from_buyer_favourites,
    get_buyer_favourite_products,
    is_product_in_favourites,
)

from django.core.paginator import Paginator


# views
def all_products_view(request):
    contact_list = get_all_products()
    paginator = Paginator(contact_list, 15)  # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    last_page = paginator.num_pages - 1
    context = {
        'page_obj': page_obj,
        'last_page': last_page,
    }
    return render(request, 'store/all_items.html', context=context)


def all_hats_view(request):
    hats = Hat.objects.all()
    paginator = Paginator(hats, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    last_page = paginator.num_pages - 1
    context = {
        'page_obj': page_obj,
        'last_page': last_page,
    }
    return render(request, 'store/all_hats.html', context=context)


def all_outwear_view(request):
    outwear = OutWear.objects.all()
    paginator = Paginator(outwear, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    last_page = paginator.num_pages - 1
    context = {
        'page_obj': page_obj,
        'last_page': last_page,
    }
    return render(request, 'store/all_outwear.html', context=context)


def all_pants_view(request):
    pants = Pants.objects.all()
    paginator = Paginator(pants, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    last_page = paginator.num_pages - 1
    context = {
        'page_obj': page_obj,
        'last_page': last_page,
    }
    return render(request, 'store/all_pants.html', context=context)


def all_shoes_view(request, ):
    shoes = Shoes.objects.all()
    paginator = Paginator(shoes, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    last_page = paginator.num_pages - 1
    context = {
        'page_obj': page_obj,
        'last_page': last_page,
    }
    return render(request, 'store/all_shoes.html', context=context)


def product_detail_view(request, product_model_slug, product_slug):
    product = get_product_by_slugs(product_model_slug, product_slug)
    product_sizes = get_product_sizes_manager(product).all()
    if hasattr(request.user, 'is_buyer') and request.user.is_buyer:
        shopping_cart_button_used = is_product_in_shopping_cart(request.user, product)
        favourites_button_used = is_product_in_favourites(request.user, product)
    else:
        shopping_cart_button_used = False
        favourites_button_used = False
    context = {
        'product': product,
        'product_sizes': product_sizes,
        'product_slug': product.product_slug,
        'shopping_cart_button_used': shopping_cart_button_used,
        'favourites_button_used': favourites_button_used,
    }
    return render(request, 'store/item_detail.html', context=context)


@permission_required('store.add_product')
def add_item_view(request, product_model_slug):
    product_model = get_product_model_by_model_slug(product_model_slug)
    product_creation_form = get_product_creation_form(product_model)
    if request.method == 'POST':
        product_creation_form = product_creation_form(
            request.POST,
            request.FILES,
            request=request,
            category_slug=product_model_slug
        )
        if product_creation_form.is_valid():
            product = product_creation_form.save()
            add_to_on_sale(request.user, product.product_code)  # add in seller on_sale collection product_code
            return HttpResponseRedirect(reverse('edit_sizes', kwargs={'product_slug': product.product_slug}))
    else:
        product_creation_form = product_creation_form(
            request=request,
            category_slug=product_model_slug
        )
    context = {
        'product_creation_form': product_creation_form,
        'category_slug': product_model_slug,
    }
    return render(request, 'store/add_item.html', context=context)


@permission_required('store.add_product')
def select_category_to_add_product_view(request):
    if request.method == 'POST':
        selected_category = request.POST['category'].lower()
        return HttpResponseRedirect(reverse('add_item', kwargs={'product_model_slug': selected_category}))
    else:
        select_category_form = SelectCategoryForm()
    context = {
        'select_category_form': select_category_form,
    }
    return render(request, 'store/select_category.html', context=context)


@permission_required('store.edit_sizes')
def edit_sizes_view(request, product_slug):
    product = get_product_by_slug(product_slug)
    if not is_seller_owner(request, product):
        return HttpResponseNotFound()
    if request.method == 'POST':
        if is_product_has_sizes(product):
            product_sizes_formset = get_product_sizes_inlineformset(product)
            product_sizes_formset = product_sizes_formset(request.POST, instance=product)
        else:
            product_sizes_formset = get_sizes_creation_formset(product)
            product_sizes_formset = product_sizes_formset(
                request.POST,
                initial=get_sizes_creation_formset_default_initial(product)
            )
        if product_sizes_formset.is_valid():
            for size_form in product_sizes_formset:
                size_form.save()
            return HttpResponseRedirect(reverse('item_detail', kwargs={
                'product_slug': product_slug,
                'product_model_slug': product.get_product_model_slug()
            }))
    else:
        if is_product_has_sizes(product):
            product_sizes_formset = get_product_sizes_inlineformset(product)
            product_sizes_formset = product_sizes_formset(instance=product)
        else:
            product_sizes_formset = get_sizes_creation_formset(product)
            product_sizes_formset = product_sizes_formset(initial=get_sizes_creation_formset_default_initial(product))
    context = {
        'product_sizes_formset': product_sizes_formset,
        'product_slug': product.product_slug,
    }
    return render(request, 'store/edit_product_sizes.html', context=context)


@permission_required('store.delete_product')
def product_delete_view(request, product_slug):
    product = get_product_by_slug(product_slug)
    if not is_seller_owner(request, product):
        return HttpResponseNotFound()
    delete_confirm_message = f'Are you sure you want to delete {product.title}?'
    if request.method == 'POST':
        if request.POST['delete']:
            pop_from_on_sale(request.user, product.product_code)
            product.delete()
        return HttpResponseRedirect(reverse('all_items'))
    else:
        return render(request, 'store/product_delete.html',
                      context={'delete_confirm_message': delete_confirm_message, 'product': product})


@permission_required('store.edit_product')
def product_edit_view(request, product_slug):
    product = get_product_by_slug(product_slug)
    if not is_seller_owner(request, product):
        return HttpResponseNotFound()
    product_edit_form_class = get_product_edit_form(product)
    if request.method == 'POST':
        product_edit_form = product_edit_form_class(request.POST, request.FILES, instance=product)
        if product_edit_form.is_valid():
            product_edit_form.save()
        return HttpResponseRedirect(reverse('all_items'))
    else:
        product_edit_form = product_edit_form_class(instance=product)
    context = {
        'product_edit_form': product_edit_form
    }
    return render(request, 'store/product_edit.html', context=context)

@permission_required('users.change_onsale')
def seller_products_on_sale_view(request):
    if not request.user.is_seller:
        return HttpResponseNotFound()
    products_on_sale = get_seller_products_on_sale(request.user)
    context = {
        'products_on_sale': products_on_sale,
    }
    return render(request, 'store/products_on_sale.html', context=context)

@permission_required('users.change_onsale')
def seller_shoes_on_sale_view(request):
    if not request.user.is_seller:
        return HttpResponseNotFound()
    shoes_on_sale = get_seller_shoes_on_sale(request.user)
    context = {
        'shoes_on_sale': shoes_on_sale,
    }
    return render(request, 'store/shoes_on_sale.html', context=context)

@permission_required('users.change_onsale')
def seller_pants_on_sale_view(request):
    if not request.user.is_seller:
        return HttpResponseNotFound()
    pants_on_sale = get_seller_pants_on_sale(request.user)
    context = {
        'pants_on_sale': pants_on_sale,
    }

store/templates/store/add_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'store/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
<form action="{% url 'add_item' category_slug %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div class="text-dark text-start">
        {{product_creation_form|crispy}}
    </div>
    <input type="submit" class="btn btn-success" value="Place">
</form>
</div>
{% endblock content %}
</body>
</html>

store/templates/store/all_hats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/all_items.html' %}
</body>
</html>

store/templates/store/all_items.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/bases/all_products_base.html' %}
</body>
</html>

store/templates/store/all_shoes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/bases/all_products_base.html' %}
</body>
</html>

store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <title>Title</title>
</head>
<body>
<div class="container-fluid text-white text-center">
    <header>
        <div class="container text-black">
            <p class="display-1">StreetWear</p>
            <p class="display-2">Shop</p>
            <p class="h6 text-end">{{user.email}}</p>
        </div>
    </header>
    <div class="container">
        <div class="row align-items-start">
            <div class="col-6 text-white">
                <div class="text-start">
                    <a href="{% url 'all_items' %}" class="btn btn-success">Main page</a>
                    <button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                      Catalog
                    </button>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'all_hats' %}">Hats</a></li>
                      <li><a class="dropdown-item" href="{% url 'all_outwear' %}">Outwear</a></li>
                      <li><a class="dropdown-item" href="{% url 'all_pants' %}">Pants</a></li>
                      <li><a class="dropdown-item" href="{% url 'all_shoes' %}">Shoes</a></li>
                    </ul>
                </div>
            </div>
            {% if request.user.is_authenticated %}
            <div class="col-6 text-white">
                <div class="text-end">
                    {% if request.user.is_buyer %}
                        <a href="{% url 'shopping_cart' %}" class="btn btn-success">Shopping Cart</a>
                        <a href="{% url 'user:buyer_profile' %}" class="btn btn-success">Profile</a>
                    {% elif request.user.is_seller %}
                        <a href="{% url 'user:seller_profile' %}" class="btn btn-success">Profile</a>
                    {% endif %}
                    <a href="{% url 'user:logout' %}" class="btn btn-success">Logout</a>
                </div>
            </div>
            {% else %}
            <div class="col-6 text-white">
                <div class="text-end">
                    <a href="{% url 'user:login' %}" class="btn btn-success">Login</a>
                    <a href="{% url 'user:signup' %}" class="btn btn-success">Sign Up</a>
                </div>
            </div>
        {% endif %}
        <hr class="bg-primary" size="5">
    </div>
</div>

{% block content %}
{% endblock content %}

</div>
</body>
</html>

store/templates/store/buyer_favourites.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/bases/buyer_profile_base.html' %}
{% for product in products %}
  <a href="{% url 'item_detail' product.product_model_slug product.product_slug %}">{{product.title}}</a>
{% endfor %}
</body>
</html>

store/templates/store/buyer_shopping_cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/bases/buyer_profile_base.html' %}
{% for product in products %}
    <p><a href="{% url 'item_detail' product.product_model_slug product.product_slug %}">{{product.title}}</a></p>
{% endfor %}
</body>
</html>

store/templates/store/hats_on_sale.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/bases/seller_profile_functionality_base.html' %}
<div class="container">
    {% for product in hats_on_sale %}
        <p>
            <div class="row">
                <div class="col-3">
                    <a href="{% url 'item_detail' product.product_model_slug product.product_slug %}">{{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'product_edit' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'edit_sizes' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}} sizes</a>
                </div>
                <div class="col-3">
                    <form action="{% url 'remove_product_from_sale' product.product_slug %}" method="POST">{% csrf_token %}
                        <input type="submit" class="btn btn-success" value="Remove From On Sale">
                    </form>
                </div>
            </div>
        </p>
    <hr class="bg-primary" size="5">
    {% endfor %}
</div>
</body>
</html>

store/templates/store/outwear_on_sale.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/bases/seller_profile_functionality_base.html' %}
<div class="container">
    {% for product in outwear_on_sale %}
        <p>
            <div class="row">
                <div class="col-3">
                    <a href="{% url 'item_detail' product.product_model_slug product.product_slug %}">{{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'product_edit' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'edit_sizes' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}} sizes</a>
                </div>
                <div class="col-3">
                    <form action="{% url 'remove_product_from_sale' product.product_slug %}" method="POST">{% csrf_token %}
                        <input type="submit" class="btn btn-success" value="Remove From On Sale">
                    </form>
                </div>
            </div>
        </p>
    <hr class="bg-primary" size="5">
    {% endfor %}
</div>
</body>
</html>

store/templates/store/pants_on_sale.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/bases/seller_profile_functionality_base.html' %}
<div class="container">
    {% for product in pants_on_sale %}
        <p>
            <div class="row">
                <div class="col-3">
                    <a href="{% url 'item_detail' product.product_model_slug product.product_slug %}">{{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'product_edit' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'edit_sizes' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}} sizes</a>
                </div>
                <div class="col-3">
                    <form action="{% url 'remove_product_from_sale' product.product_slug %}" method="POST">{% csrf_token %}
                        <input type="submit" class="btn btn-success" value="Remove From On Sale">
                    </form>
                </div>
            </div>
        </p>
    <hr class="bg-primary" size="5">
    {% endfor %}
</div>
</body>
</html>

store/templates/store/product_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/item_detail.html' %}
{% block content %}
<div class="text-dark">
    <form method="POST">{% csrf_token %}
        <input type="radio" name="delete" id="Yes" value="Y">
        <label for="Yes">Yes</label>
        <input type="radio" name="delete" id="No" value="">
        <label for="No">No</label>
        <input type="submit" class="btn btn-danger" value="Submit">
    </form>
</div>
{% endblock content %}
</body>
</html>

store/templates/store/product_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/base.html' %}
{% load crispy_forms_tags %}
<div class="container">
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{product_edit_form|crispy}}
        <input type="submit" class="btn btn-success" value="Edit">
    </form>
</div>
</body>
</html>

store/templates/store/products_on_sale.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/bases/seller_profile_functionality_base.html' %}
<div class="container text-dark text-start">
    <div class="container">
        {% for product in products_on_sale %}
        <p>
            <div class="row">
                <div class="col-3">
                    <a href="{% url 'item_detail' product.product_model_slug product.product_slug %}">{{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'product_edit' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'edit_sizes' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}} sizes</a>
                </div>
                <div class="col-3">
                    <form action="{% url 'remove_product_from_sale' product.product_slug %}" method="POST">{% csrf_token %}
                        <input type="submit" class="btn btn-success" value="Remove From On Sale">
                    </form>
                </div>
            </div>
        </p>
        <hr class="bg-primary" size="5">
        {% endfor %}
    </div>
</div>
</body>
</html>

store/templates/store/shoes_on_sale.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'store/bases/seller_profile_functionality_base.html' %}
<div class="container">
    {% for product in shoes_on_sale %}
        <p>
            <div class="row">
                <div class="col-3">
                    <a href="{% url 'item_detail' product.product_model_slug product.product_slug %}">{{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'product_edit' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}}</a>
                </div>
                <div class="col-3">
                    <a href="{% url 'edit_sizes' product.product_slug %}" class="btn btn-success text-end">Edit {{product.title}} sizes</a>
                </div>
                <div class="col-3">
                    <form action="{% url 'remove_product_from_sale' product.product_slug %}" method="POST">{% csrf_token %}
                        <input type="submit" class="btn btn-success" value="Remove From On Sale">
                    </form>
                </div>
            </div>
        </p>
    <hr class="bg-primary" size="5">
    {% endfor %}
</div>
</body>
</html>